# Generated by Django 5.1.2 on 2025-02-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('commercial', 'Comercial'), ('entrepreneur', 'Emprendedor')], default='commercial', help_text='Tipo de negocio', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_primary_to_secondary',
            field=models.BooleanField(default=True),
        ),
    ]
