# Generated by Django 5.1.2 on 2025-06-29 23:59

import business.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessprofile_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Atributo de Sucursal',
                'verbose_name_plural': 'Atributos de Sucursal',
            },
        ),
        migrations.CreateModel(
            name='BranchBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Beneficio de Sucursal',
                'verbose_name_plural': 'Beneficios de Sucursal',
            },
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='business_profiles/default.png', null=True, upload_to=business.models.business_profile_image_path, verbose_name='Imagen de perfil'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('is_headquarter', models.BooleanField(default=False, help_text='Marca si esta sucursal es la casa matriz', verbose_name='Casa Matriz')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='business.businessprofile')),
                ('attributes', models.ManyToManyField(blank=True, related_name='branches', to='business.branchattribute')),
                ('benefits', models.ManyToManyField(blank=True, related_name='branches', to='business.branchbenefit')),
            ],
            options={
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('website', 'Sitio Web')], max_length=20)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='business.businessprofile')),
            ],
            options={
                'unique_together': {('business', 'platform')},
            },
        ),
    ]
