# Generated by Django 5.1.2 on 2025-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_branchattribute_branchbenefit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
