# Generated by Django 5.1.2 on 2025-07-08 00:30

from django.db import migrations

def populate_branch_attributes(apps, schema_editor):
    BranchAttribute = apps.get_model('business', 'BranchAttribute')
    attributes = [
        'Wifi',
        'Estacionamiento',
        'Pet friendly',
        'Valet Parking',
        'Coworking',
    ]
    for name in attributes:
        BranchAttribute.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_socialmedialink_url'),
    ]

    operations = [
        migrations.RunPython(populate_branch_attributes),
    ]
