# Generated by Django 5.1.2 on 2026-09-12 17:38

from django.db import migrations, models


def migrate_website_to_link(apps, schema_editor):
    SocialMediaLink = apps.get_model('business', 'SocialMediaLink')
    SocialMediaLink.objects.filter(platform='website').update(platform='link')
    # Defensive: assign order by index within (business, platform) so the
    # UniqueConstraint added right after this never conflicts, even though
    # the old unique_together made duplicates impossible up to this point.
    for business_id, platform in (
        SocialMediaLink.objects.order_by()
        .values_list('business_id', 'platform')
        .distinct()
    ):
        rows = SocialMediaLink.objects.filter(
            business_id=business_id, platform=platform
        ).order_by('id')
        for index, row in enumerate(rows):
            if row.order != index:
                row.order = index
                row.save(update_fields=['order'])


def reverse_link_to_website(apps, schema_editor):
    SocialMediaLink = apps.get_model('business', 'SocialMediaLink')
    SocialMediaLink.objects.filter(platform='link').update(platform='website')


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_update_currency_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='label',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('link', 'Enlaces')], max_length=20),
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['platform', 'order', 'id']},
        ),
        migrations.RunPython(migrate_website_to_link, reverse_link_to_website),
        migrations.AddConstraint(
            model_name='socialmedialink',
            constraint=models.UniqueConstraint(fields=('business', 'platform', 'order'), name='uniq_social_link_business_platform_order'),
        ),
    ]
