# Generated by Django 5.1.2 on 2026-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_social_links_multi_entry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialmedialink',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__in', ('whatsapp', 'link')), _negated=True), fields=('business', 'platform'), name='uniq_social_link_business_platform_single_entry'),
        ),
    ]
