# Generated by Django 5.1.2 on 2025-07-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_populate_branch_attributes'),
        ('products', '0002_productcategory_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='business.businessprofile'),
        ),
    ]
