# Generated by Django 5.1.2 on 2025-07-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_productaddon_productmedia_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='has_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='multibuy_option',
            field=models.CharField(blank=True, choices=[('2x1', '2x1'), ('3x2', '3x2')], help_text='Oferta tipo 2x1, 3x2, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stopper',
            field=models.CharField(blank=True, choices=[('FAVORITE', 'Favorito del mes'), ('RECOMMENDED', 'Recomendado')], help_text='Tipo de stopper activo (opcional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='multibuy_option',
            field=models.CharField(blank=True, choices=[('2x1', '2x1'), ('3x2', '3x2')], help_text='Oferta tipo 2x1, 3x2, etc.', max_length=10, null=True),
        ),
    ]
