# Generated by Django 5.1.2 on 2025-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['media_type', 'order']},
        ),
        migrations.AddField(
            model_name='productmedia',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
