# Generated by Django 5.1.2 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
