# Generated by Django 5.1.2 on 2026-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_update_currency_names'),
        ('products', '0014_dedupe_recommended_stopper_per_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('stopper', 'RECOMMENDED')), fields=('category',), name='unique_recommended_stopper_per_category'),
        ),
    ]
